AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  ClassifyImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: classify.handler
      Runtime: python2.7
      CodeUri: dl_lambdas/
      Timeout: 300
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/LambdaExecutionRole']]
      Events:
        ResizeImage:
            Type: Api
            Properties:
                Path: '/image/resize'
                Method: post

