AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  ResizeImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: image_processing.resize_image
      Runtime: python3.6
      CodeUri: lambda/
      Timeout: 300
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/LambdaExecutionRole']]
      Events:
        ResizeImage:
            Type: Api
            Properties:
                Path: '/image/resize'
                Method: post
