AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  ResizeImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process.handler
      Runtime: python2.7
      CodeUri: image_processing/
      Timeout: 300
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/LambdaExecutionRole']]
      Events:
        ResizeImage:
            Type: Api
            Properties:
                Path: '/image/resize'
                Method: post

  Yolo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'Yolo'
      Handler: classify_image.handler
      Runtime: python2.7
      CodeUri: yolo/
      Timeout: 300
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/LambdaExecutionRole']]
      Events:
        ResizeImage:
            Type: Api
            Properties:
                Path: '/image/resize'
                Method: post
