AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  ProcessImageApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger-export.yml
      StageName: Prod
      Variables:
        ProcessImage: !Ref ProcessImage

  ProcessImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: process.handler
      Runtime: python2.7
      CodeUri: lambdas/image_processing/
      Timeout: 300
      MemorySize: 3008
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/LambdaExecutionRole']]
      Events:
        ProcessImage:
            Type: Api
            Properties:
                RestApiId: !Ref ProcessImageApi
                Path: '/process_image'
                Method: post

Outputs:
  ProcessImageApi:
    Description: "API Endpoint for ProcessImageApi"
    Value: !Ref ProcessImageApi
